server:
  port: 8555
spring:
  application:
    name: redis5
  # lettuce配置，二选一就好
  redis:
    lettuce:
      pool:
        max-active: 20 # 最大连接数
        max-idle: 20 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
        max-wait: -1ms # 最大阻塞等待时间，负值表示没有限制
    cluster:
      nodes:
      - 192.168.0.90:7010
      - 192.168.0.90:7011
      - 192.168.0.90:7012
      - 192.168.0.90:7013
      - 192.168.0.90:7014
      - 192.168.0.90:7015
#    password: admin # redis密码

# jedis配置，二选一就好
redis:
  maxTotal: 20 # 最大连接数
  maxIdle: 20 # 最大空闲连接数
  minIdle: 0 # 最小空闲连接数
  connectionTimeout: 5000 # 连接超时时间
  soTimeout: 10000 # 读取超时时间
  maxAttempts: 1 # 最大尝试次数
#  passWord: admin # redis密码
  servers:
    - 192.168.0.90:7010
    - 192.168.0.90:7011
    - 192.168.0.90:7012
    - 192.168.0.90:7013
    - 192.168.0.90:7014
    - 192.168.0.90:7015

# 日志配置文件路径
logging:
  config: config/log4j2.xml

# 优雅停机
management:
  server:
    port: 8556
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true